image: node:latest
 
Build:
  stage: build
  script:
    - docker build .

Unit-Tests:
  stage: test
  script:
    - npm install
    - npm test
Echo:
  stage: echo
  script:  
   - echo "Hello local gitlab-runner"
